const signals = [
  {icon:'⌑',type:'policy',title:'FTC opens antitrust review into cloud marketplace',source:'Reuters · 18 min ago',entity:'MSFT',risk:'Regulatory',sentiment:'Negative',severity:'Critical',confidence:94},
  {icon:'◒',type:'market',title:'Treasury yields climb as inflation outlook shifts',source:'GDELT · 32 min ago',entity:'TLT',risk:'Macro / rates',sentiment:'Negative',severity:'Critical',confidence:91},
  {icon:'⌁',type:'supply',title:'Chip suppliers flag extended lead times into Q4',source:'Bloomberg · 1 hr ago',entity:'NVDA',risk:'Supply chain',sentiment:'Negative',severity:'High',confidence:87},
  {icon:'◌',type:'social',title:'Retail sentiment turns sharply bearish on regional banks',source:'Social stream · 2 hr ago',entity:'KRE',risk:'Market sentiment',sentiment:'Negative',severity:'High',confidence:78},
  {icon:'↗',type:'market',title:'Energy prices ease after OPEC supply update',source:'NewsAPI · 3 hr ago',entity:'XLE',risk:'Commodity',sentiment:'Positive',severity:'Medium',confidence:83},
  {icon:'⌑',type:'policy',title:'EU advances new AI disclosure requirements',source:'GDELT · 4 hr ago',entity:'XLK',risk:'Regulatory',sentiment:'Neutral',severity:'Medium',confidence:72},
  {icon:'◌',type:'social',title:'Consumer confidence rebounds in latest survey',source:'Social stream · 5 hr ago',entity:'XLY',risk:'Market sentiment',sentiment:'Positive',severity:'Medium',confidence:69},
  {icon:'◒',type:'market',title:'Dollar strengthens as rate-cut expectations cool',source:'Reuters · 6 hr ago',entity:'UUP',risk:'FX / rates',sentiment:'Negative',severity:'High',confidence:81}
];
const streams = [
  {time:'09:42',title:'FTC opens antitrust review into cloud marketplace',meta:'Reuters · MSFT',pill:'CRITICAL',level:'critical'},
  {time:'09:28',title:'Treasury yields climb as inflation outlook shifts',meta:'GDELT · TLT',pill:'CRITICAL',level:'critical'},
  {time:'09:01',title:'Chip suppliers flag extended lead times into Q4',meta:'Bloomberg · NVDA',pill:'HIGH',level:'high'},
  {time:'08:47',title:'Retail sentiment turns bearish on regional banks',meta:'Social stream · KRE',pill:'HIGH',level:'high'}
];
let activeFilter='all',showAll=false;
const rows=document.getElementById('signal-rows');
function renderSignals(){const filtered=activeFilter==='all'?signals:signals.filter(s=>s.severity===activeFilter);const visible=showAll?filtered:filtered.slice(0,4);rows.innerHTML=visible.map(s=>`<tr><td><div class="event-cell"><span class="event-icon ${s.type}">${s.icon}</span><span class="event-copy"><b>${s.title}</b><small>${s.source}</small></span></div></td><td><span class="entity-tag">${s.entity}</span></td><td><span class="risk-type">${s.risk}</span></td><td><span class="sentiment ${s.sentiment.toLowerCase()}"><i>${s.sentiment==='Negative'?'↘':s.sentiment==='Positive'?'↗':'→'}</i>${s.sentiment}</span></td><td><span class="severity ${s.severity.toLowerCase()}">${s.severity}</span></td><td><span class="confidence"><span class="confidence-track"><i style="width:${s.confidence}%"></i></span>${s.confidence}%</span></td><td><button class="row-more" aria-label="Signal actions">···</button></td></tr>`).join('');document.getElementById('signal-count').textContent=`Showing ${visible.length} of ${filtered.length} ${activeFilter==='all'?'priority signals':activeFilter.toLowerCase()+' signals'}`;document.querySelectorAll('.filter-button').forEach(b=>b.classList.toggle('active',b.dataset.filter===activeFilter));document.getElementById('view-all').innerHTML=showAll?'Show fewer <b>↑</b>':'View all signals <b>→</b>';}
function renderStream(){document.getElementById('stream-list').innerHTML=streams.map(s=>`<div class="stream-event"><span class="stream-time">${s.time}</span><span class="stream-body"><b>${s.title}</b><small>${s.meta}</small></span><span class="stream-pill ${s.level==='high'?'medium':''}">${s.pill}</span></div>`).join('')}
document.querySelectorAll('.filter-button').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;showAll=false;renderSignals()}));
document.getElementById('view-all').addEventListener('click',()=>{showAll=!showAll;renderSignals()});
const toast=document.getElementById('toast');let toastTimer;
function notify(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}
document.getElementById('export-btn').addEventListener('click',()=>{const csv=[['Event','Source','Entity','Risk type','Sentiment','Severity','Confidence'],...signals.map(s=>[s.title,s.source,s.entity,s.risk,s.sentiment,s.severity,`${s.confidence}%`])].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='meridian-risk-signals.csv';a.click();URL.revokeObjectURL(a.href);notify('Risk signal report exported')});
document.querySelectorAll('.nav-item[href^="#"]').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));a.classList.add('active')}));
document.querySelectorAll('.workspace-switch,.control-button,.select-button,.round-more').forEach(b=>b.addEventListener('click',()=>notify('This control is available in the connected workspace.')));
const eventInput=document.getElementById('event-input');
eventInput.addEventListener('input',()=>document.getElementById('char-count').textContent=`${eventInput.value.length} / 500`);
document.getElementById('analyze-form').addEventListener('submit',e=>{e.preventDefault();const text=eventInput.value.trim();if(!text){notify('Add an event headline or post to analyze');eventInput.focus();return}const lower=text.toLowerCase();const groups=[['Regulatory',['antitrust','regulat','lawsuit','ban','rule','fine','ftc','sec']],['Supply chain',['supply','shortage','delay','supplier','shipment','lead time']],['Macro / rates',['inflation','rate','treasury','yield','federal reserve','fed','currency']],['Market sentiment',['sentiment','shares','stock','investor','selloff','rally']],['Company event',['earnings','revenue','outlook','recall','cyber','layoff']]];const match=groups.find(([,words])=>words.some(w=>lower.includes(w)));const risk=match?match[0]:'General market';const negative=['fall','drop','declin','miss','cut','loss','bearish','risk','delay','shortage','fine','ban','selloff','lawsuit','warning','inflation','climb','surge','attack','recall'].some(w=>lower.includes(w));const positive=['rise','gain','beat','growth','record','upgrade','rebound','ease','bullish','profit'].some(w=>lower.includes(w));const sentiment=negative?'Negative':positive?'Positive':'Neutral';const severity=negative&&['antitrust','fine','ban','lawsuit','shortage','recall','attack'].some(w=>lower.includes(w))?'High':negative?'Medium':'Low';const tickerMatch=text.match(/\b[A-Z]{2,5}\b/);const entity=tickerMatch?tickerMatch[0]:'Unmatched';const confidence=Math.min(96,65+Math.min(25,text.split(/\s+/).length));const result=document.getElementById('analysis-result');result.innerHTML=`<div class="result-heading"><b>Structured event output</b><span>DEMO MODEL</span></div><div class="result-tags"><span class="result-tag"><strong>ENTITY</strong>${entity}</span><span class="result-tag"><strong>RISK TYPE</strong>${risk}</span><span class="result-tag"><strong>SENTIMENT</strong>${sentiment}</span><span class="result-tag"><strong>SEVERITY</strong>${severity}</span><span class="result-tag"><strong>CONFIDENCE</strong>${confidence}%</span></div><p class="result-explanation">Rule-based demonstration. A production engine would use entity linking, trained event classification, calibrated confidence, and portfolio exposure to rank this signal.</p>`;result.classList.add('visible')});
const now=new Date();document.getElementById('date-label').textContent=new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'2-digit'}).format(now).toUpperCase().replace(',','');renderSignals();renderStream();
