const { v4: uuidv4 } = require('uuid');

const buildUnderlyingStory = ({
  primaryEntity = 'unknown entity',
  primaryEntityId = null,
  title = 'General financial story',
  eventType = 'general_financial_event',
  entities = [],
  topics = [],
  sourceNames = [],
  supportingEventIds = [],
  sourceCount = 1,
  independentSourceCount = 1,
  confidence = 0.5,
  clusterReason = 'new_story',
  status = 'NEW',
  summary = '',
  explanation = {},
  storyKey = null,
  createdAt = new Date().toISOString(),
  updatedAt = new Date().toISOString(),
  firstSeenAt = new Date().toISOString(),
  lastSeenAt = new Date().toISOString(),
  severity = 'moderate',
}) => ({
  id: uuidv4(),
  primary_entity: String(primaryEntity).trim().toLowerCase() || 'unknown entity',
  primary_entity_id: primaryEntityId,
  title: String(title).trim() || 'General financial story',
  event_type: String(eventType).trim().toLowerCase() || 'general_financial_event',
  entities: [...new Set((entities || []).map((item) => String(item).trim().toLowerCase()).filter(Boolean))],
  topics: [...new Set((topics || []).map((item) => String(item).trim().toLowerCase()).filter(Boolean))],
  source_names: [...new Set((sourceNames || []).map((item) => String(item).trim()).filter(Boolean))],
  supporting_event_ids: [...new Set((supportingEventIds || []).map((item) => String(item)).filter(Boolean))],
  source_count: Number(sourceCount || 0),
  independent_source_count: Number(independentSourceCount || 0),
  confidence: Number(confidence || 0),
  cluster_reason: clusterReason,
  status,
  summary,
  explanation: {
    reason: clusterReason,
    ...explanation,
  },
  story_key: storyKey || `story:${Date.now()}:${Math.random().toString(36).slice(2, 8)}`,
  created_at: createdAt,
  updated_at: updatedAt,
  first_seen_at: firstSeenAt,
  last_seen_at: lastSeenAt,
  severity,
});

module.exports = {
  buildUnderlyingStory,
};
